version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-boycott
    environment:
      MYSQL_DATABASE: boycott_db
      MYSQL_ROOT_PASSWORD: zainebss
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: boycott-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/boycott_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: zainebss
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  db_data:

