apiVersion: v1
kind: Service
metadata:
  name: boycott-app
  namespace: boycott
spec:
  selector:
    app: boycott-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort

